import type { Listing, Testimonial, Agent } from './types';

export const listings: Listing[] = [
  {
    id: '1',
    title: 'The Pinnacle at Highland Park',
    suburb: 'Highland Park',
    city: 'Los Angeles',
    price: 3250000,
    bedrooms: 3,
    bathrooms: 2,
    status: 'For Sale',
    imageUrl: 'https://picsum.photos/seed/listing1/600/400',
    videoUrl: 'https://videos.pexels.com/video-files/3209828/3209828-hd_1280_720_25fps.mp4',
    imageHint: 'modern suburban house',
    isFeatured: true,
  },
  {
    id: '2',
    title: 'The Grand Estate',
    suburb: 'Beverly Hills',
    city: 'Los Angeles',
    price: 4500000,
    bedrooms: 4,
    bathrooms: 3,
    status: 'For Sale',
    imageUrl: 'https://picsum.photos/seed/listing2/600/400',
    videoUrl: 'https://videos.pexels.com/video-files/5495801/5495801-hd_1280_720_25fps.mp4',
    imageHint: 'large white house',
    isFeatured: true,
  },
  {
    id: '3',
    title: 'Modern Luxury Villa',
    suburb: 'Highland Park',
    city: 'Los Angeles',
    price: 2890000,
    bedrooms: 3,
    bathrooms: 3,
    status: 'For Sale',
    imageUrl: 'https://picsum.photos/seed/listing3/600/400',
    videoUrl: 'https://videos.pexels.com/video-files/5387439/5387439-hd_1280_720_25fps.mp4',
    imageHint: 'modern dark house',
    isFeatured: true,
  },
  {
    id: '4',
    title: 'The Modern at Highland Park',
    suburb: 'Highland Park',
    city: 'Los Angeles',
    price: 3750000,
    bedrooms: 4,
    bathrooms: 3,
    status: 'For Sale',
    imageUrl: 'https://picsum.photos/seed/listing4/600/400',
    videoUrl: 'https://videos.pexels.com/video-files/5932822/5932822-hd_1280_720_24fps.mp4',
    imageHint: 'house with large windows',
    isFeatured: true,
  },
  {
    id: '5',
    title: 'Classic Family Home',
    suburb: 'Highland Park',
    city: 'Los Angeles',
    price: 2100000,
    bedrooms: 3,
    bathrooms: 2,
    status: 'For Sale',
    imageUrl: 'https://picsum.photos/seed/listing5/600/400',
    videoUrl: 'https://videos.pexels.com/video-files/8099233/8099233-hd_1920_1080_30fps.mp4',
    imageHint: 'classic american house',
    isFeatured: true,
  },
   {
    id: '6',
    title: 'Greenwich Modern House',
    suburb: 'Highland Park',
    city: 'Los Angeles',
    price: 1950000,
    bedrooms: 2,
    bathrooms: 2,
    status: 'For Sale',
    imageUrl: 'https://picsum.photos/seed/listing6/600/400',
    videoUrl: 'https://videos.pexels.com/video-files/8100346/8100346-hd_1920_1080_30fps.mp4',
    imageHint: 'house with green roof',
    isFeatured: true,
  },
];

export const testimonials: Testimonial[] = [
    {
      id: '1',
      name: 'Sarah Silverman',
      role: 'Home Buyer',
      quote: "Working with this team was a pleasure. They understood our vision and helped us find a property that exceeded our expectations. We couldn't have done it without them!",
      imageUrl: "https://picsum.photos/seed/testimonial1/100/100",
      imageHint: "smiling man glasses"
    },
    {
      id: '2',
      name: 'John Doe',
      role: 'Property Seller',
      quote: "The sale of our home was smooth and professional. The team's marketing strategy was brilliant, attracting numerous buyers and securing a fantastic price. Highly recommended.",
      imageUrl: "https://picsum.photos/seed/testimonial2/100/100",
      imageHint: "professional woman"
    },
];

export const agents: Agent[] = [
  {
    id: '1',
    name: 'Johnathan Doe',
    role: 'Lead Real Estate Agent',
    email: 'john.doe@lprealty.com',
    bio: "With over a decade of experience in luxury real estate, Johnathan has a proven track record of securing the best deals for his clients. His market knowledge is unparalleled.",
    imageUrl: "https://picsum.photos/seed/agent1/400/600",
    imageHint: "professional man portrait",
    initials: "JD",
  },
  {
    id: '2',
    name: 'Jane Smith',
    role: 'Senior Property Consultant',
    email: 'jane.smith@lprealty.com',
    bio: "Jane's passion for architecture and design gives her a unique eye for properties. She excels at matching clients with homes that are not just houses, but works of art.",
    imageUrl: "https://picsum.photos/seed/agent2/400/600",
    imageHint: "professional woman portrait",
    initials: "JS",
  },
  {
    id: '3',
    name: 'Mike Johnson',
    role: 'Investment Specialist',
    email: 'mike.johnson@lprealty.com',
    bio: "Specializing in high-yield investment properties, Mike helps clients build robust real estate portfolios that generate long-term wealth.",
    imageUrl: "https://picsum.photos/seed/agent3/400/600",
    imageHint: "smiling man corporate",
    initials: "MJ",
  },
  {
    id: '4',
    name: 'Emily Williams',
    role: 'Client Relations Manager',
    email: 'emily.williams@lprealty.com',
    bio: "Emily ensures every client's journey is seamless and enjoyable. Her attention to detail and commitment to service are second to none.",
    imageUrl: "https://picsum.photos/seed/agent4/400/600",
    imageHint: "friendly woman professional",
    initials: "EW",
  },
  {
    id: '5',
    name: 'Chris Brown',
    role: 'Marketing Director',
    email: 'chris.brown@lprealty.com',
    bio: "The mastermind behind our innovative marketing campaigns, Chris leverages cutting-edge media to showcase properties like never before.",
    imageUrl: "https://picsum.photos/seed/agent5/400/600",
    imageHint: "creative director portrait",
    initials: "CB",
  },
];
