import type { Listing, Testimonial } from './types';

export const listings: Listing[] = [
  {
    id: '1',
    title: 'The Pinnacle at Highland Park',
    suburb: 'Highland Park',
    city: 'Los Angeles',
    price: 3250000,
    bedrooms: 3,
    bathrooms: 2,
    status: 'For Sale',
    imageUrl: 'https://picsum.photos/seed/listing1/600/400',
    imageHint: 'modern suburban house',
    isFeatured: true,
  },
  {
    id: '2',
    title: 'The Grand Estate',
    suburb: 'Beverly Hills',
    city: 'Los Angeles',
    price: 4500000,
    bedrooms: 4,
    bathrooms: 3,
    status: 'For Sale',
    imageUrl: 'https://picsum.photos/seed/listing2/600/400',
    imageHint: 'large white house',
    isFeatured: true,
  },
  {
    id: '3',
    title: 'Modern Luxury Villa',
    suburb: 'Highland Park',
    city: 'Los Angeles',
    price: 2890000,
    bedrooms: 3,
    bathrooms: 3,
    status: 'For Sale',
    imageUrl: 'https://picsum.photos/seed/listing3/600/400',
    imageHint: 'modern dark house',
    isFeatured: true,
  },
  {
    id: '4',
    title: 'The Modern at Highland Park',
    suburb: 'Highland Park',
    city: 'Los Angeles',
    price: 3750000,
    bedrooms: 4,
    bathrooms: 3,
    status: 'For Sale',
    imageUrl: 'https://picsum.photos/seed/listing4/600/400',
    imageHint: 'house with large windows',
    isFeatured: true,
  },
  {
    id: '5',
    title: 'Classic Family Home',
    suburb: 'Highland Park',
    city: 'Los Angeles',
    price: 2100000,
    bedrooms: 3,
    bathrooms: 2,
    status: 'For Sale',
    imageUrl: 'https://picsum.photos/seed/listing5/600/400',
    imageHint: 'classic american house',
    isFeatured: true,
  },
   {
    id: '6',
    title: 'Greenwich Modern House',
    suburb: 'Highland Park',
    city: 'Los Angeles',
    price: 1950000,
    bedrooms: 2,
    bathrooms: 2,
    status: 'For Sale',
    imageUrl: 'https://picsum.photos/seed/listing6/600/400',
    imageHint: 'house with green roof',
    isFeatured: true,
  },
];

export const testimonials: Testimonial[] = [
    {
      id: '1',
      name: 'Sarah Silverman',
      role: 'Home Buyer',
      quote: "Working with this team was a pleasure. They understood our vision and helped us find a property that exceeded our expectations. We couldn't have done it without them!",
      imageUrl: "https://picsum.photos/seed/testimonial1/100/100",
      imageHint: "smiling man glasses"
    },
    {
      id: '2',
      name: 'John Doe',
      role: 'Property Seller',
      quote: "The sale of our home was smooth and professional. The team's marketing strategy was brilliant, attracting numerous buyers and securing a fantastic price. Highly recommended.",
      imageUrl: "https://picsum.photos/seed/testimonial2/100/100",
      imageHint: "professional woman"
    },
];
