import type { Listing, Testimonial, Agent } from './types';

export const listings: Listing[] = [
  {
    id: '1',
    title: 'The Pinnacle at Highland Park',
    suburb: 'Highland Park',
    city: 'Los Angeles',
    price: 3250000,
    bedrooms: 3,
    bathrooms: 2,
    status: 'For Sale',
    imageUrl: 'https://picsum.photos/seed/listing1/600/400',
    videoUrl: 'https://videos.pexels.com/video-files/3209828/3209828-hd_1280_720_25fps.mp4',
    imageHint: 'modern suburban house',
    isFeatured: true,
  },
  {
    id: '2',
    title: 'The Grand Estate',
    suburb: 'Beverly Hills',
    city: 'Los Angeles',
    price: 4500000,
    bedrooms: 4,
    bathrooms: 3,
    status: 'For Sale',
    imageUrl: 'https://picsum.photos/seed/listing2/600/400',
    videoUrl: 'https://videos.pexels.com/video-files/5495801/5495801-hd_1280_720_25fps.mp4',
    imageHint: 'large white house',
    isFeatured: true,
  },
  {
    id: '3',
    title: 'Modern Luxury Villa',
    suburb: 'Highland Park',
    city: 'Los Angeles',
    price: 2890000,
    bedrooms: 3,
    bathrooms: 3,
    status: 'For Sale',
    imageUrl: 'https://picsum.photos/seed/listing3/600/400',
    videoUrl: 'https://videos.pexels.com/video-files/5387439/5387439-hd_1280_720_25fps.mp4',
    imageHint: 'modern dark house',
    isFeatured: true,
  },
  {
    id: '4',
    title: 'The Modern at Highland Park',
    suburb: 'Highland Park',
    city: 'Los Angeles',
    price: 3750000,
    bedrooms: 4,
    bathrooms: 3,
    status: 'For Sale',
    imageUrl: 'https://picsum.photos/seed/listing4/600/400',
    videoUrl: 'https://videos.pexels.com/video-files/5932822/5932822-hd_1280_720_24fps.mp4',
    imageHint: 'house with large windows',
    isFeatured: true,
  },
  {
    id: '5',
    title: 'Classic Family Home',
    suburb: 'Highland Park',
    city: 'Los Angeles',
    price: 2100000,
    bedrooms: 3,
    bathrooms: 2,
    status: 'For Sale',
    imageUrl: 'https://picsum.photos/seed/listing5/600/400',
    videoUrl: 'https://videos.pexels.com/video-files/8099233/8099233-hd_1920_1080_30fps.mp4',
    imageHint: 'classic american house',
    isFeatured: true,
  },
   {
    id: '6',
    title: 'Greenwich Modern House',
    suburb: 'Highland Park',
    city: 'Los Angeles',
    price: 1950000,
    bedrooms: 2,
    bathrooms: 2,
    status: 'For Sale',
    imageUrl: 'https://picsum.photos/seed/listing6/600/400',
    videoUrl: 'https://videos.pexels.com/video-files/8100346/8100346-hd_1920_1080_30fps.mp4',
    imageHint: 'house with green roof',
    isFeatured: true,
  },
];

export const testimonials: Testimonial[] = [
    {
      id: '1',
      name: 'Sarah Silverman',
      role: 'Home Buyer',
      quote: "Working with this team was a pleasure. They understood our vision and helped us find a property that exceeded our expectations. We couldn't have done it without them!",
      imageUrl: "https://picsum.photos/seed/testimonial1/100/100",
      imageHint: "smiling man glasses"
    },
    {
      id: '2',
      name: 'John Doe',
      role: 'Property Seller',
      quote: "The sale of our home was smooth and professional. The team's marketing strategy was brilliant, attracting numerous buyers and securing a fantastic price. Highly recommended.",
      imageUrl: "https://picsum.photos/seed/testimonial2/100/100",
      imageHint: "professional woman"
    },
];

export const agents: Agent[] = [
  {
    id: '1',
    name: 'Taylor Davidson',
    role: 'CEO & Agent',
    email: 'taylor@lprealty.co.za',
    bio: "Taylor has spent over a decade in South Africa's high-end residential market, closing more than R500 million in transactions. He leads LP Realty with a precise, relationship-first approach that consistently delivers above-expectation results for both buyers and sellers.",
    imageUrl: "https://picsum.photos/seed/agent1/400/600",
    imageHint: "professional man portrait",
    initials: "TD",
  },
  {
    id: '2',
    name: 'Sibiya Sibiya',
    role: 'Host & Lead Agent',
    email: 'sibiya@lprealty.co.za',
    bio: "As the face of Let's Prop In, Sibiya has redefined property marketing in the social media era. He combines deep residential expertise with a platform reach that turns a half-million engaged followers into a pipeline of serious, qualified buyers.",
    imageUrl: "https://picsum.photos/seed/agent2/400/600",
    imageHint: "smiling man professional",
    initials: "SS",
  },
  {
    id: '3',
    name: 'Bradley Dare',
    role: 'Head of Operations',
    email: 'bradley@lprealty.co.za',
    bio: "With over 500 closed deals across sales, rentals, and investment properties, Bradley is the engine behind LP Realty's day-to-day excellence. Clients rely on him for straight answers, seamless processes, and outcomes that hold up long after transfer.",
    imageUrl: "https://picsum.photos/seed/agent3/400/600",
    imageHint: "smiling man corporate",
    initials: "BD",
  },
  {
    id: '4',
    name: 'Neo Baloyi',
    role: 'Head of Media',
    email: 'neo@letspropinmedia.co.za',
    bio: "Neo operates at the intersection of real estate, architecture, and visual storytelling. As LP Realty's creative lead, he produces cinematic listing content that makes properties impossible to ignore — and turns quality presentation into measurable sales results.",
    imageUrl: "https://picsum.photos/seed/agent4/400/600",
    imageHint: "creative director portrait",
    initials: "NB",
  },
];
